### ISSUE TITLE
size error

### ISSUE THREAD

**Issue by adammaj1** [ttoinou/MandelbrotDE#1]
Hi, 
I have
*  ubuntu 16.04 LTS
*  processing 3.3.3
* cloned this repo

After opening files and run command
there is an error : 
size of the sketch can not be determined from your code.

?

Adam

**Comment by ttoinou** [comment]
Hi !
Processing 3 is too recent for my code and I don't know the new stuff sorry. I think I coded this with Processing 2 so just download this version

**Comment by adammaj1** [comment]
Hi,
Works. 
Thx.
